language: ruby
before_install:
  - nvm install stable
  - nvm use stable
  - npm install -g yarn
before_script:
  - rake assets:precompile
  - rm -f db/test.sqlite3
  - RAILS_ENV=test rails db:create
script: bundle exec rails test
