language: ruby
before_install:
  - nvm install stable
  - nvm use stable
  - npm install -g yarn
before_script:
  - bundle exec rails assets:precompile
  - rm -f db/test.sqlite3
  - RAILS_ENV=test bundle exec rails db:create
script: bundle exec rails test
