language: ruby
before_install:
  - nvm install stable
  - nvm use stable
  - npm install -g yarn
before_script:
  # - bundle exec rake assets:precompile
  - rm -f db/test.db
  - RAILS_ENV=test rails db:create
script: bundle exec rails test
